
# Roundcube Docker image
image: roundcube/roundcubemail:1.4.x-apache
imagePullPolicy: IfNotPresent

config:
  desKey:
  defaultLanguage: en_US
  defaultSkin: larry
  plugins: ""  # comma-separated list of additional plugins to be loaded
  uploadMaxFilesize: 25M


# Configuration for an external database (not deployed within this chart)
externalDatabase:
  # external database type. supported: mysql, pgsql, sqlite
  type: pgsql
  host:
  port: 5432
  name: roundcube
  user: postgres
  password: postgres


# IMAP settings
imap:
  # hostname or IP address of IMAP server
  host:

  # IMAP port. Default ports depending on encryption setting:
  #   143 - none, STARTTLS
  #   993 - SSL/TLS (recommended)
  port: 993

  # Transport encryption. Please change port accordingly. Allowed values:
  #   none     - no encryption
  #   starttls - use STARTTLS
  #   ssltls   - use SSL/TLS (recommended)
  encryption: ssltls

  # IMAP username
  username:

  # IMAP password
  password:


# SMTP settings
smtp:
  # hostname or IP address of SMTP server
  host:

  # SMTP port. Default ports depending on encryption setting:
  #    25 - none
  #   465 - SSL/TLS
  #   587 - STARTTLS (recommended)
  port: 465

  # Transport encryption. Please change port accordingly. Allowed values:
  #   none     - no encryption
  #   starttls - use STARTTLS
  #   ssltls   - use SSL/TLS (recommended)
  encryption: ssltls

  # SMTP username (use "%u" tp use IMAP username)
  username: "%u"

  # SMTP password (use "%p" tp use IMAP password)
  password: "%p"


secret:
  additionalLabels: {}
  additionalAnnotations: {}


deployment:
  replicas: 2
  port: 80

  additionalLabels: {}
  additionalAnnotations: {}

  podAffinityPreset: ""
  podAntiAffinityPreset: hard
  affinity: {}


service:
  port: 80

  additionalLabels: {}
  additionalAnnotations: {}

  ipFamilyPolicy: PreferDualStack


ingress:
  host:
  path: "/"
  class: nginx

  additionalLabels: {}
  additionalAnnotations: {}


pdb:
  enabled: true
  minAvailable: 1
  maxUnavailable: ""

  additionalLabels: {}
  additionalAnnotations: {}
