
## Roundcube Docker image
image: roundcube/roundcubemail:1.5.2-apache
imagePullPolicy: IfNotPresent

config:
  desKey:
  defaultLanguage: en_US
  defaultSkin: larry
  uploadMaxFilesize: 25M

  plugins:
    ## https://github.com/roundcube/roundcubemail/blob/master/plugins/managesieve/config.inc.php.dist
    managesieve:
      enabled: false
      config:
        host: "%h"
        port: 4190
        useTls: true

    ## Context menu plugin: Adds context menus with common tasks to various parts of Roundcube
    ## https://packagist.org/packages/johndoh/contextmenu
    ## Example for a dynamically installed plugin (via composer)
    contextmenu:

      ## Enabled installing and loading the plugin.
      enabled: false

      ## composer package information
      composerPackage:
        name: "johndoh/contextmenu"
        version: "3.3"

  ## Custom PHP configuration
  customRoundcubeConfig: |
    /*
     * Custom Roundcube Configuration values
     * Check https://github.com/roundcube/roundcubemail/wiki/Configuration for available options.
     */

    // $config['skin_logo'] = "";
    // $config['support_url'] = "https://roundcube.net/";

  customPhpConfig: |
    ## Configure custom memory limit for PHP
    # memory_limit=128M


## Configuration for an external database (not deployed within this chart)
## When working with a NetworkPolicy, add an egress rule to networkPolicy.egress.additionalRules to allow access to the database.
externalDatabase:
  ## external database type. supported: mysql, pgsql, sqlite
  type: pgsql
  host:
  port: 5432
  name: roundcube
  user: postgres
  password: postgres

## IMAP settings
imap:
  ## hostname or IP address of IMAP server
  host:

  ## IMAP port. Default ports depending on encryption setting:
  ##   143 - none, STARTTLS
  ##   993 - SSL/TLS (recommended)
  port: 993

  ## Transport encryption. Please change port accordingly. Allowed values:
  ##   none     - no encryption
  ##   starttls - use STARTTLS
  ##   ssltls   - use SSL/TLS (recommended)
  encryption: ssltls

  ## IMAP username
  username:

  ## IMAP password
  password:


## SMTP settings
smtp:
  ## hostname or IP address of SMTP server
  host:

  ## SMTP port. Default ports depending on encryption setting:
  ##    25 - none
  ##   465 - SSL/TLS
  ##   587 - STARTTLS (recommended)
  port: 465

  ## Transport encryption. Please change port accordingly. Allowed values:
  ##   none     - no encryption
  ##   starttls - use STARTTLS
  ##   ssltls   - use SSL/TLS (recommended)
  encryption: ssltls

  ## SMTP username (use "%u" tp use IMAP username)
  username: "%u"

  ## SMTP password (use "%p" tp use IMAP password)
  password: "%p"


configMap:
  additionalLabels: {}
  additionalAnnotations: {}


secret:
  additionalLabels: {}
  additionalAnnotations: {}


deployment:
  replicas: 2
  port: 80

  additionalLabels: {}
  additionalAnnotations: {}

  podAffinityPreset: ""
  podAntiAffinityPreset: hard
  affinity: {}

  ## Configure resource allocation and limits
  # resources:
  #   requests:
  #     memory: "256Mi"
  #     cpu: "1000m"
  #   limits:
  #     memory: "256Mi"
  #     cpu: "1000m"


service:
  port: 80

  additionalLabels: {}
  additionalAnnotations: {}

  ipFamilyPolicy: PreferDualStack


ingress:
  host:
  path: "/"
  class: nginx

  additionalLabels: {}
  additionalAnnotations: {}


pdb:
  enabled: true
  minAvailable: 1
  maxUnavailable: ""

  additionalLabels: {}
  additionalAnnotations: {}


## A NetworkPolicy can prevent unauthorized access to remote hosts on network level.
## By default, if enabled, the NetworkPolicy allows to connect to any IP with the IMAP and SMTP ports configured above.
## This also applies for the managesieve plugin, if enabled.
## More information on network policies: https://kubernetes.io/docs/concepts/services-networking/network-policies/
networkPolicy:

  ## Create a NetworkPolicy Resource
  enabled: false

  egress:
    imap:

      ## Explicitely configure allowed peers for the IMAP connection.
      ## See https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#networkpolicypeer-v1-networking-k8s-io for all possible options.
      peers:
        - ipBlock:
            cidr: 0.0.0.0/0

    smtp:

      ## Explicitely configure allowed peers for the SMTP connection.
      ## See https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#networkpolicypeer-v1-networking-k8s-io for all possible options.
      peers:
        - ipBlock:
            cidr: 0.0.0.0/0

    managesieve:

      ## Explicitely configure allowed peers for the managesieve connection. Will only be used if managesieve plugin is enabled.
      ## See https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#networkpolicypeer-v1-networking-k8s-io for all possible options.
      peers:
        - ipBlock:
            cidr: 0.0.0.0/0

    ## Add additional, custom egress rules.
    ## See https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#networkpolicyegressrule-v1-networking-k8s-io.
    additionalRules: []
    ## Example rule for a zalando postgres cluster called "shared-postgres" in namespace "postgres"
    #  - to:
    #    - namespaceSelector:
    #        matchLabels:
    #          kubernetes.io/metadata.name: postgres
    #    - podSelector:
    #        matchLabels:
    #          cluster-name: shared-postgres
    #    ports:
    #      - port: 5432
    #        protocol: TCP


  ## Additional labels for the NetworkPolicy
  additionalLabels: {}

  ## Additional annotations for the NetworkPolicy
  additionalAnnotations: {}
