---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.configMap.additionalLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.configMap.additionalLabels "context" $) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.configMap.additionalAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.configMap.additionalAnnotations "context" $) | nindent 4 }}
    {{- end }}
data:
  php.ini: |
    {{- .Values.config.customPhpConfig | default "" | nindent 4 }}
  roundcube.config.php: |
    <?php
    {{ range $plugin, $settings := .Values.config.plugins }}
    // generated configuration for plugin {{ $plugin }}
    {{- if $settings -}}{{- if $settings.enabled -}}{{- range $key, $value := $settings.config }}
    $config['{{ $plugin }}_{{ $key }}'] = {{ if kindIs "string" $value }}{{ $value | quote }}{{ else }}{{ $value }}{{ end }};
    {{- end -}}{{- end -}}{{- end }}
    {{ end }}

    // custom roundcube config
    {{- .Values.config.customRoundcubeConfig | default "" | nindent 4 -}}
