---
{{- if .Values.pdb.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.networkPolicy.additionalLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.networkPolicy.additionalLabels "context" $) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.networkPolicy.additionalAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.networkPolicy.additionalAnnotations "context" $) | nindent 4 }}
    {{- end }}
spec:
  podSelector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
  policyTypes:
    - Egress
  egress:
    - to:
      - ipBlock:
          cidr: 0.0.0.0/0
          except:
            {{- if .Values.networkPolicy.egress.blockPrivateNetworks }}
            {{- .Values.networkPolicy.privateNetworks | toYaml | nindent 12 }}
            {{- end }}
      ports:
        - protocol: TCP
          port: {{ .Values.smtp.port }}
        - protocol: TCP
          port: {{ .Values.imap.port }}
        - protocol: TCP
          port: {{ .Values.externalDatabase.port }}
    - ports:
      - port: 53
        protocol: UDP
      - port: 53
        protocol: TCP
{{- end -}}
