---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
  annotations:
type: Opaque
stringData:
  smtpUsername: "{{ .Values.smtp.username }}"
  smtpPassword: "{{ .Values.smtp.password }}"
  dbUsername: "{{ .Values.externalDatabase.user }}"
  dbPassword: "{{ .Values.externalDatabase.password }}"
